services:
  postgres:
    image: postgres:16.4
    container_name: perflab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: perf_lab_dev
      POSTGRES_DB: perf_lab
    ports:
      - "5432:5432"
    volumes:
      - perflab_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d perf_lab"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  perflab_pgdata:
